trigger: none

jobs:
  - template: ../../eng/pipelines/templates/jobs/archetype-sdk-testsarchetype-sdk-tests.yml
    parameters:
      Matrix:
        Linux - Java 8 (AzureCloud):
          OSVmImage: 'ubuntu-18.04'
          JavaVersion: '1.8'
          DisplayName: 'Linux - Java 8'
          CloudType: AzureCloud
          AZURE_TEST_HTTP_CLIENTS: netty
      ServiceDirectory: appconfiguration
      Artifacts:
        - name: azure-data-appconfiguration
          groupId: com.azure
          safeName: azuredataappconfiguration
      EnvVars:
        AZURE_TEST_MODE: RECORD
        AZURE_APPCONFIG_CONNECTION_STRING: $(AZURE_APPCONFIG_CONNECTION_STRING)
        AZURE_CLIENT_ID: $(aad-azure-sdk-test-client-id)
        AZURE_CLIENT_SECRET: $(aad-azure-sdk-test-client-secret)
        AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id)
