spring:
  cloud:
    azure:
      eventhub:
        connection-string:
        checkpoint-storage-account:
        checkpoint-access-key:
        checkpoint-container:
    function:
      definition: consume;supply;
    stream:
      poller:
        initial-delay: 3000
        fixed-delay: 1000
      bindings:
        consume-in-0:
          destination:
          group: $Default
        supply-out-0:
          destination:

      eventhub:
        bindings:
          consume-in-0:
            consumer:
              checkpoint-mode: MANUAL
      default:
        producer:
          errorChannelEnabled: true